<?php


/**
 * Skeleton subclass for representing a row from the 'user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/04/13 14:47:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserProfile extends BaseUserProfile {
	public function __toString(){
		$full_name= $this->getNombre() ." ". $this->getApellido();
		return $full_name;
	}
} // UserProfile
