generator:
  class: sfPropelGenerator
  param:
    model_class:           UserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              UserProfile
    plural:                UserProfiles
    route_prefix:          user_profile
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
