<?php

/**
 * Base class that represents a row from the 'patogenos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 * @package    lib.model.om
 */
abstract class BasePatogenos extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PatogenosPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nombre_prueba field.
	 * @var        string
	 */
	protected $nombre_prueba;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the resultado_id field.
	 * @var        int
	 */
	protected $resultado_id;

	/**
	 * The value for the campo_resultado_patogeno_id field.
	 * @var        int
	 */
	protected $campo_resultado_patogeno_id;

	/**
	 * The value for the prueba_bioquimica_id field.
	 * @var        int
	 */
	protected $prueba_bioquimica_id;

	/**
	 * The value for the positivo_negativo_id field.
	 * @var        int
	 */
	protected $positivo_negativo_id;

	/**
	 * @var        Resultado
	 */
	protected $aResultado;

	/**
	 * @var        CampoResultadoPatogeno
	 */
	protected $aCampoResultadoPatogeno;

	/**
	 * @var        PruebaBioquimica
	 */
	protected $aPruebaBioquimica;

	/**
	 * @var        PositivoNegativo
	 */
	protected $aPositivoNegativo;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PatogenosPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nombre_prueba] column value.
	 * 
	 * @return     string
	 */
	public function getNombrePrueba()
	{
		return $this->nombre_prueba;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [resultado_id] column value.
	 * 
	 * @return     int
	 */
	public function getResultadoId()
	{
		return $this->resultado_id;
	}

	/**
	 * Get the [campo_resultado_patogeno_id] column value.
	 * 
	 * @return     int
	 */
	public function getCampoResultadoPatogenoId()
	{
		return $this->campo_resultado_patogeno_id;
	}

	/**
	 * Get the [prueba_bioquimica_id] column value.
	 * 
	 * @return     int
	 */
	public function getPruebaBioquimicaId()
	{
		return $this->prueba_bioquimica_id;
	}

	/**
	 * Get the [positivo_negativo_id] column value.
	 * 
	 * @return     int
	 */
	public function getPositivoNegativoId()
	{
		return $this->positivo_negativo_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PatogenosPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nombre_prueba] column.
	 * 
	 * @param      string $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setNombrePrueba($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre_prueba !== $v) {
			$this->nombre_prueba = $v;
			$this->modifiedColumns[] = PatogenosPeer::NOMBRE_PRUEBA;
		}

		return $this;
	} // setNombrePrueba()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PatogenosPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PatogenosPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [resultado_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setResultadoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->resultado_id !== $v) {
			$this->resultado_id = $v;
			$this->modifiedColumns[] = PatogenosPeer::RESULTADO_ID;
		}

		if ($this->aResultado !== null && $this->aResultado->getId() !== $v) {
			$this->aResultado = null;
		}

		return $this;
	} // setResultadoId()

	/**
	 * Set the value of [campo_resultado_patogeno_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setCampoResultadoPatogenoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->campo_resultado_patogeno_id !== $v) {
			$this->campo_resultado_patogeno_id = $v;
			$this->modifiedColumns[] = PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID;
		}

		if ($this->aCampoResultadoPatogeno !== null && $this->aCampoResultadoPatogeno->getId() !== $v) {
			$this->aCampoResultadoPatogeno = null;
		}

		return $this;
	} // setCampoResultadoPatogenoId()

	/**
	 * Set the value of [prueba_bioquimica_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setPruebaBioquimicaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->prueba_bioquimica_id !== $v) {
			$this->prueba_bioquimica_id = $v;
			$this->modifiedColumns[] = PatogenosPeer::PRUEBA_BIOQUIMICA_ID;
		}

		if ($this->aPruebaBioquimica !== null && $this->aPruebaBioquimica->getId() !== $v) {
			$this->aPruebaBioquimica = null;
		}

		return $this;
	} // setPruebaBioquimicaId()

	/**
	 * Set the value of [positivo_negativo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patogenos The current object (for fluent API support)
	 */
	public function setPositivoNegativoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->positivo_negativo_id !== $v) {
			$this->positivo_negativo_id = $v;
			$this->modifiedColumns[] = PatogenosPeer::POSITIVO_NEGATIVO_ID;
		}

		if ($this->aPositivoNegativo !== null && $this->aPositivoNegativo->getId() !== $v) {
			$this->aPositivoNegativo = null;
		}

		return $this;
	} // setPositivoNegativoId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre_prueba = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->created_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->updated_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resultado_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->campo_resultado_patogeno_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->prueba_bioquimica_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->positivo_negativo_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Patogenos object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aResultado !== null && $this->resultado_id !== $this->aResultado->getId()) {
			$this->aResultado = null;
		}
		if ($this->aCampoResultadoPatogeno !== null && $this->campo_resultado_patogeno_id !== $this->aCampoResultadoPatogeno->getId()) {
			$this->aCampoResultadoPatogeno = null;
		}
		if ($this->aPruebaBioquimica !== null && $this->prueba_bioquimica_id !== $this->aPruebaBioquimica->getId()) {
			$this->aPruebaBioquimica = null;
		}
		if ($this->aPositivoNegativo !== null && $this->positivo_negativo_id !== $this->aPositivoNegativo->getId()) {
			$this->aPositivoNegativo = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PatogenosPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aResultado = null;
			$this->aCampoResultadoPatogeno = null;
			$this->aPruebaBioquimica = null;
			$this->aPositivoNegativo = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePatogenos:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PatogenosPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePatogenos:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePatogenos:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(PatogenosPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(PatogenosPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePatogenos:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PatogenosPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aResultado !== null) {
				if ($this->aResultado->isModified() || $this->aResultado->isNew()) {
					$affectedRows += $this->aResultado->save($con);
				}
				$this->setResultado($this->aResultado);
			}

			if ($this->aCampoResultadoPatogeno !== null) {
				if ($this->aCampoResultadoPatogeno->isModified() || $this->aCampoResultadoPatogeno->isNew()) {
					$affectedRows += $this->aCampoResultadoPatogeno->save($con);
				}
				$this->setCampoResultadoPatogeno($this->aCampoResultadoPatogeno);
			}

			if ($this->aPruebaBioquimica !== null) {
				if ($this->aPruebaBioquimica->isModified() || $this->aPruebaBioquimica->isNew()) {
					$affectedRows += $this->aPruebaBioquimica->save($con);
				}
				$this->setPruebaBioquimica($this->aPruebaBioquimica);
			}

			if ($this->aPositivoNegativo !== null) {
				if ($this->aPositivoNegativo->isModified() || $this->aPositivoNegativo->isNew()) {
					$affectedRows += $this->aPositivoNegativo->save($con);
				}
				$this->setPositivoNegativo($this->aPositivoNegativo);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PatogenosPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PatogenosPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PatogenosPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aResultado !== null) {
				if (!$this->aResultado->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aResultado->getValidationFailures());
				}
			}

			if ($this->aCampoResultadoPatogeno !== null) {
				if (!$this->aCampoResultadoPatogeno->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCampoResultadoPatogeno->getValidationFailures());
				}
			}

			if ($this->aPruebaBioquimica !== null) {
				if (!$this->aPruebaBioquimica->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPruebaBioquimica->getValidationFailures());
				}
			}

			if ($this->aPositivoNegativo !== null) {
				if (!$this->aPositivoNegativo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPositivoNegativo->getValidationFailures());
				}
			}


			if (($retval = PatogenosPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PatogenosPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNombrePrueba();
				break;
			case 2:
				return $this->getCreatedAt();
				break;
			case 3:
				return $this->getUpdatedAt();
				break;
			case 4:
				return $this->getResultadoId();
				break;
			case 5:
				return $this->getCampoResultadoPatogenoId();
				break;
			case 6:
				return $this->getPruebaBioquimicaId();
				break;
			case 7:
				return $this->getPositivoNegativoId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PatogenosPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNombrePrueba(),
			$keys[2] => $this->getCreatedAt(),
			$keys[3] => $this->getUpdatedAt(),
			$keys[4] => $this->getResultadoId(),
			$keys[5] => $this->getCampoResultadoPatogenoId(),
			$keys[6] => $this->getPruebaBioquimicaId(),
			$keys[7] => $this->getPositivoNegativoId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PatogenosPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNombrePrueba($value);
				break;
			case 2:
				$this->setCreatedAt($value);
				break;
			case 3:
				$this->setUpdatedAt($value);
				break;
			case 4:
				$this->setResultadoId($value);
				break;
			case 5:
				$this->setCampoResultadoPatogenoId($value);
				break;
			case 6:
				$this->setPruebaBioquimicaId($value);
				break;
			case 7:
				$this->setPositivoNegativoId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PatogenosPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombrePrueba($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCreatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUpdatedAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setResultadoId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCampoResultadoPatogenoId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPruebaBioquimicaId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPositivoNegativoId($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PatogenosPeer::DATABASE_NAME);

		if ($this->isColumnModified(PatogenosPeer::ID)) $criteria->add(PatogenosPeer::ID, $this->id);
		if ($this->isColumnModified(PatogenosPeer::NOMBRE_PRUEBA)) $criteria->add(PatogenosPeer::NOMBRE_PRUEBA, $this->nombre_prueba);
		if ($this->isColumnModified(PatogenosPeer::CREATED_AT)) $criteria->add(PatogenosPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PatogenosPeer::UPDATED_AT)) $criteria->add(PatogenosPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(PatogenosPeer::RESULTADO_ID)) $criteria->add(PatogenosPeer::RESULTADO_ID, $this->resultado_id);
		if ($this->isColumnModified(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID)) $criteria->add(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, $this->campo_resultado_patogeno_id);
		if ($this->isColumnModified(PatogenosPeer::PRUEBA_BIOQUIMICA_ID)) $criteria->add(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, $this->prueba_bioquimica_id);
		if ($this->isColumnModified(PatogenosPeer::POSITIVO_NEGATIVO_ID)) $criteria->add(PatogenosPeer::POSITIVO_NEGATIVO_ID, $this->positivo_negativo_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PatogenosPeer::DATABASE_NAME);

		$criteria->add(PatogenosPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Patogenos (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombrePrueba($this->nombre_prueba);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setResultadoId($this->resultado_id);

		$copyObj->setCampoResultadoPatogenoId($this->campo_resultado_patogeno_id);

		$copyObj->setPruebaBioquimicaId($this->prueba_bioquimica_id);

		$copyObj->setPositivoNegativoId($this->positivo_negativo_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Patogenos Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PatogenosPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PatogenosPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Resultado object.
	 *
	 * @param      Resultado $v
	 * @return     Patogenos The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setResultado(Resultado $v = null)
	{
		if ($v === null) {
			$this->setResultadoId(NULL);
		} else {
			$this->setResultadoId($v->getId());
		}

		$this->aResultado = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Resultado object, it will not be re-added.
		if ($v !== null) {
			$v->addPatogenos($this);
		}

		return $this;
	}


	/**
	 * Get the associated Resultado object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Resultado The associated Resultado object.
	 * @throws     PropelException
	 */
	public function getResultado(PropelPDO $con = null)
	{
		if ($this->aResultado === null && ($this->resultado_id !== null)) {
			$this->aResultado = ResultadoPeer::retrieveByPk($this->resultado_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aResultado->addPatogenoss($this);
			 */
		}
		return $this->aResultado;
	}

	/**
	 * Declares an association between this object and a CampoResultadoPatogeno object.
	 *
	 * @param      CampoResultadoPatogeno $v
	 * @return     Patogenos The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCampoResultadoPatogeno(CampoResultadoPatogeno $v = null)
	{
		if ($v === null) {
			$this->setCampoResultadoPatogenoId(NULL);
		} else {
			$this->setCampoResultadoPatogenoId($v->getId());
		}

		$this->aCampoResultadoPatogeno = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the CampoResultadoPatogeno object, it will not be re-added.
		if ($v !== null) {
			$v->addPatogenos($this);
		}

		return $this;
	}


	/**
	 * Get the associated CampoResultadoPatogeno object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     CampoResultadoPatogeno The associated CampoResultadoPatogeno object.
	 * @throws     PropelException
	 */
	public function getCampoResultadoPatogeno(PropelPDO $con = null)
	{
		if ($this->aCampoResultadoPatogeno === null && ($this->campo_resultado_patogeno_id !== null)) {
			$this->aCampoResultadoPatogeno = CampoResultadoPatogenoPeer::retrieveByPk($this->campo_resultado_patogeno_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCampoResultadoPatogeno->addPatogenoss($this);
			 */
		}
		return $this->aCampoResultadoPatogeno;
	}

	/**
	 * Declares an association between this object and a PruebaBioquimica object.
	 *
	 * @param      PruebaBioquimica $v
	 * @return     Patogenos The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPruebaBioquimica(PruebaBioquimica $v = null)
	{
		if ($v === null) {
			$this->setPruebaBioquimicaId(NULL);
		} else {
			$this->setPruebaBioquimicaId($v->getId());
		}

		$this->aPruebaBioquimica = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PruebaBioquimica object, it will not be re-added.
		if ($v !== null) {
			$v->addPatogenos($this);
		}

		return $this;
	}


	/**
	 * Get the associated PruebaBioquimica object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PruebaBioquimica The associated PruebaBioquimica object.
	 * @throws     PropelException
	 */
	public function getPruebaBioquimica(PropelPDO $con = null)
	{
		if ($this->aPruebaBioquimica === null && ($this->prueba_bioquimica_id !== null)) {
			$this->aPruebaBioquimica = PruebaBioquimicaPeer::retrieveByPk($this->prueba_bioquimica_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPruebaBioquimica->addPatogenoss($this);
			 */
		}
		return $this->aPruebaBioquimica;
	}

	/**
	 * Declares an association between this object and a PositivoNegativo object.
	 *
	 * @param      PositivoNegativo $v
	 * @return     Patogenos The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPositivoNegativo(PositivoNegativo $v = null)
	{
		if ($v === null) {
			$this->setPositivoNegativoId(NULL);
		} else {
			$this->setPositivoNegativoId($v->getId());
		}

		$this->aPositivoNegativo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PositivoNegativo object, it will not be re-added.
		if ($v !== null) {
			$v->addPatogenos($this);
		}

		return $this;
	}


	/**
	 * Get the associated PositivoNegativo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PositivoNegativo The associated PositivoNegativo object.
	 * @throws     PropelException
	 */
	public function getPositivoNegativo(PropelPDO $con = null)
	{
		if ($this->aPositivoNegativo === null && ($this->positivo_negativo_id !== null)) {
			$this->aPositivoNegativo = PositivoNegativoPeer::retrieveByPk($this->positivo_negativo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPositivoNegativo->addPatogenoss($this);
			 */
		}
		return $this->aPositivoNegativo;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aResultado = null;
			$this->aCampoResultadoPatogeno = null;
			$this->aPruebaBioquimica = null;
			$this->aPositivoNegativo = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePatogenos:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePatogenos::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePatogenos
