<?php

/**
 * Base static class for performing query and update operations on the 'patogenos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 * @package    lib.model.om
 */
abstract class BasePatogenosPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'patogenos';

	/** the related Propel class for this table */
	const OM_CLASS = 'Patogenos';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Patogenos';

	/** the related TableMap class for this table */
	const TM_CLASS = 'PatogenosTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 8;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'patogenos.ID';

	/** the column name for the NOMBRE_PRUEBA field */
	const NOMBRE_PRUEBA = 'patogenos.NOMBRE_PRUEBA';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'patogenos.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'patogenos.UPDATED_AT';

	/** the column name for the RESULTADO_ID field */
	const RESULTADO_ID = 'patogenos.RESULTADO_ID';

	/** the column name for the CAMPO_RESULTADO_PATOGENO_ID field */
	const CAMPO_RESULTADO_PATOGENO_ID = 'patogenos.CAMPO_RESULTADO_PATOGENO_ID';

	/** the column name for the PRUEBA_BIOQUIMICA_ID field */
	const PRUEBA_BIOQUIMICA_ID = 'patogenos.PRUEBA_BIOQUIMICA_ID';

	/** the column name for the POSITIVO_NEGATIVO_ID field */
	const POSITIVO_NEGATIVO_ID = 'patogenos.POSITIVO_NEGATIVO_ID';

	/**
	 * An identiy map to hold any loaded instances of Patogenos objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Patogenos[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'NombrePrueba', 'CreatedAt', 'UpdatedAt', 'ResultadoId', 'CampoResultadoPatogenoId', 'PruebaBioquimicaId', 'PositivoNegativoId', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'nombrePrueba', 'createdAt', 'updatedAt', 'resultadoId', 'campoResultadoPatogenoId', 'pruebaBioquimicaId', 'positivoNegativoId', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NOMBRE_PRUEBA, self::CREATED_AT, self::UPDATED_AT, self::RESULTADO_ID, self::CAMPO_RESULTADO_PATOGENO_ID, self::PRUEBA_BIOQUIMICA_ID, self::POSITIVO_NEGATIVO_ID, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'nombre_prueba', 'created_at', 'updated_at', 'resultado_id', 'campo_resultado_patogeno_id', 'prueba_bioquimica_id', 'positivo_negativo_id', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'NombrePrueba' => 1, 'CreatedAt' => 2, 'UpdatedAt' => 3, 'ResultadoId' => 4, 'CampoResultadoPatogenoId' => 5, 'PruebaBioquimicaId' => 6, 'PositivoNegativoId' => 7, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'nombrePrueba' => 1, 'createdAt' => 2, 'updatedAt' => 3, 'resultadoId' => 4, 'campoResultadoPatogenoId' => 5, 'pruebaBioquimicaId' => 6, 'positivoNegativoId' => 7, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NOMBRE_PRUEBA => 1, self::CREATED_AT => 2, self::UPDATED_AT => 3, self::RESULTADO_ID => 4, self::CAMPO_RESULTADO_PATOGENO_ID => 5, self::PRUEBA_BIOQUIMICA_ID => 6, self::POSITIVO_NEGATIVO_ID => 7, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'nombre_prueba' => 1, 'created_at' => 2, 'updated_at' => 3, 'resultado_id' => 4, 'campo_resultado_patogeno_id' => 5, 'prueba_bioquimica_id' => 6, 'positivo_negativo_id' => 7, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. PatogenosPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(PatogenosPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(PatogenosPeer::ID);
		$criteria->addSelectColumn(PatogenosPeer::NOMBRE_PRUEBA);
		$criteria->addSelectColumn(PatogenosPeer::CREATED_AT);
		$criteria->addSelectColumn(PatogenosPeer::UPDATED_AT);
		$criteria->addSelectColumn(PatogenosPeer::RESULTADO_ID);
		$criteria->addSelectColumn(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID);
		$criteria->addSelectColumn(PatogenosPeer::PRUEBA_BIOQUIMICA_ID);
		$criteria->addSelectColumn(PatogenosPeer::POSITIVO_NEGATIVO_ID);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Patogenos
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = PatogenosPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return PatogenosPeer::populateObjects(PatogenosPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			PatogenosPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Patogenos $value A Patogenos object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Patogenos $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Patogenos object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Patogenos) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Patogenos object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Patogenos Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to patogenos
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = PatogenosPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = PatogenosPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				PatogenosPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Resultado table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinResultado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CampoResultadoPatogeno table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCampoResultadoPatogeno(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PruebaBioquimica table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPruebaBioquimica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PositivoNegativo table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPositivoNegativo(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with their Resultado objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinResultado(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);
		ResultadoPeer::addSelectColumns($criteria);

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ResultadoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ResultadoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = ResultadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ResultadoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Patogenos) to $obj2 (Resultado)
				$obj2->addPatogenos($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with their CampoResultadoPatogeno objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCampoResultadoPatogeno(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);
		CampoResultadoPatogenoPeer::addSelectColumns($criteria);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CampoResultadoPatogenoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CampoResultadoPatogenoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = CampoResultadoPatogenoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CampoResultadoPatogenoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Patogenos) to $obj2 (CampoResultadoPatogeno)
				$obj2->addPatogenos($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with their PruebaBioquimica objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPruebaBioquimica(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);
		PruebaBioquimicaPeer::addSelectColumns($criteria);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PruebaBioquimicaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PruebaBioquimicaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = PruebaBioquimicaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PruebaBioquimicaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Patogenos) to $obj2 (PruebaBioquimica)
				$obj2->addPatogenos($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with their PositivoNegativo objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPositivoNegativo(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);
		PositivoNegativoPeer::addSelectColumns($criteria);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PositivoNegativoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PositivoNegativoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = PositivoNegativoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PositivoNegativoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Patogenos) to $obj2 (PositivoNegativo)
				$obj2->addPatogenos($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Patogenos objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol2 = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);

		ResultadoPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (ResultadoPeer::NUM_COLUMNS - ResultadoPeer::NUM_LAZY_LOAD_COLUMNS);

		CampoResultadoPatogenoPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CampoResultadoPatogenoPeer::NUM_COLUMNS - CampoResultadoPatogenoPeer::NUM_LAZY_LOAD_COLUMNS);

		PruebaBioquimicaPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (PruebaBioquimicaPeer::NUM_COLUMNS - PruebaBioquimicaPeer::NUM_LAZY_LOAD_COLUMNS);

		PositivoNegativoPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (PositivoNegativoPeer::NUM_COLUMNS - PositivoNegativoPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Resultado rows

			$key2 = ResultadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = ResultadoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = ResultadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ResultadoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Patogenos) to the collection in $obj2 (Resultado)
				$obj2->addPatogenos($obj1);
			} // if joined row not null

			// Add objects for joined CampoResultadoPatogeno rows

			$key3 = CampoResultadoPatogenoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = CampoResultadoPatogenoPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$cls = CampoResultadoPatogenoPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CampoResultadoPatogenoPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Patogenos) to the collection in $obj3 (CampoResultadoPatogeno)
				$obj3->addPatogenos($obj1);
			} // if joined row not null

			// Add objects for joined PruebaBioquimica rows

			$key4 = PruebaBioquimicaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = PruebaBioquimicaPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$cls = PruebaBioquimicaPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PruebaBioquimicaPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Patogenos) to the collection in $obj4 (PruebaBioquimica)
				$obj4->addPatogenos($obj1);
			} // if joined row not null

			// Add objects for joined PositivoNegativo rows

			$key5 = PositivoNegativoPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = PositivoNegativoPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$cls = PositivoNegativoPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					PositivoNegativoPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Patogenos) to the collection in $obj5 (PositivoNegativo)
				$obj5->addPatogenos($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Resultado table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptResultado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related CampoResultadoPatogeno table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCampoResultadoPatogeno(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PruebaBioquimica table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPruebaBioquimica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PositivoNegativo table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPositivoNegativo(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PatogenosPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PatogenosPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with all related objects except Resultado.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptResultado(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol2 = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);

		CampoResultadoPatogenoPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (CampoResultadoPatogenoPeer::NUM_COLUMNS - CampoResultadoPatogenoPeer::NUM_LAZY_LOAD_COLUMNS);

		PruebaBioquimicaPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PruebaBioquimicaPeer::NUM_COLUMNS - PruebaBioquimicaPeer::NUM_LAZY_LOAD_COLUMNS);

		PositivoNegativoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (PositivoNegativoPeer::NUM_COLUMNS - PositivoNegativoPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined CampoResultadoPatogeno rows

				$key2 = CampoResultadoPatogenoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CampoResultadoPatogenoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = CampoResultadoPatogenoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CampoResultadoPatogenoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj2 (CampoResultadoPatogeno)
				$obj2->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PruebaBioquimica rows

				$key3 = PruebaBioquimicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = PruebaBioquimicaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = PruebaBioquimicaPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PruebaBioquimicaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj3 (PruebaBioquimica)
				$obj3->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PositivoNegativo rows

				$key4 = PositivoNegativoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PositivoNegativoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = PositivoNegativoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PositivoNegativoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj4 (PositivoNegativo)
				$obj4->addPatogenos($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with all related objects except CampoResultadoPatogeno.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCampoResultadoPatogeno(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol2 = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);

		ResultadoPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (ResultadoPeer::NUM_COLUMNS - ResultadoPeer::NUM_LAZY_LOAD_COLUMNS);

		PruebaBioquimicaPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PruebaBioquimicaPeer::NUM_COLUMNS - PruebaBioquimicaPeer::NUM_LAZY_LOAD_COLUMNS);

		PositivoNegativoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (PositivoNegativoPeer::NUM_COLUMNS - PositivoNegativoPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Resultado rows

				$key2 = ResultadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ResultadoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = ResultadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ResultadoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj2 (Resultado)
				$obj2->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PruebaBioquimica rows

				$key3 = PruebaBioquimicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = PruebaBioquimicaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = PruebaBioquimicaPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PruebaBioquimicaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj3 (PruebaBioquimica)
				$obj3->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PositivoNegativo rows

				$key4 = PositivoNegativoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PositivoNegativoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = PositivoNegativoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PositivoNegativoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj4 (PositivoNegativo)
				$obj4->addPatogenos($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with all related objects except PruebaBioquimica.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPruebaBioquimica(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol2 = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);

		ResultadoPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (ResultadoPeer::NUM_COLUMNS - ResultadoPeer::NUM_LAZY_LOAD_COLUMNS);

		CampoResultadoPatogenoPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CampoResultadoPatogenoPeer::NUM_COLUMNS - CampoResultadoPatogenoPeer::NUM_LAZY_LOAD_COLUMNS);

		PositivoNegativoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (PositivoNegativoPeer::NUM_COLUMNS - PositivoNegativoPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::POSITIVO_NEGATIVO_ID, PositivoNegativoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Resultado rows

				$key2 = ResultadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ResultadoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = ResultadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ResultadoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj2 (Resultado)
				$obj2->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined CampoResultadoPatogeno rows

				$key3 = CampoResultadoPatogenoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CampoResultadoPatogenoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = CampoResultadoPatogenoPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CampoResultadoPatogenoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj3 (CampoResultadoPatogeno)
				$obj3->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PositivoNegativo rows

				$key4 = PositivoNegativoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PositivoNegativoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = PositivoNegativoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PositivoNegativoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj4 (PositivoNegativo)
				$obj4->addPatogenos($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Patogenos objects pre-filled with all related objects except PositivoNegativo.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Patogenos objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPositivoNegativo(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PatogenosPeer::addSelectColumns($criteria);
		$startcol2 = (PatogenosPeer::NUM_COLUMNS - PatogenosPeer::NUM_LAZY_LOAD_COLUMNS);

		ResultadoPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (ResultadoPeer::NUM_COLUMNS - ResultadoPeer::NUM_LAZY_LOAD_COLUMNS);

		CampoResultadoPatogenoPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CampoResultadoPatogenoPeer::NUM_COLUMNS - CampoResultadoPatogenoPeer::NUM_LAZY_LOAD_COLUMNS);

		PruebaBioquimicaPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (PruebaBioquimicaPeer::NUM_COLUMNS - PruebaBioquimicaPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PatogenosPeer::RESULTADO_ID, ResultadoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::CAMPO_RESULTADO_PATOGENO_ID, CampoResultadoPatogenoPeer::ID, $join_behavior);

		$criteria->addJoin(PatogenosPeer::PRUEBA_BIOQUIMICA_ID, PruebaBioquimicaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePatogenosPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PatogenosPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PatogenosPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PatogenosPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PatogenosPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Resultado rows

				$key2 = ResultadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ResultadoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = ResultadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ResultadoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj2 (Resultado)
				$obj2->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined CampoResultadoPatogeno rows

				$key3 = CampoResultadoPatogenoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CampoResultadoPatogenoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = CampoResultadoPatogenoPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CampoResultadoPatogenoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj3 (CampoResultadoPatogeno)
				$obj3->addPatogenos($obj1);

			} // if joined row is not null

				// Add objects for joined PruebaBioquimica rows

				$key4 = PruebaBioquimicaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PruebaBioquimicaPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = PruebaBioquimicaPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PruebaBioquimicaPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Patogenos) to the collection in $obj4 (PruebaBioquimica)
				$obj4->addPatogenos($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasePatogenosPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasePatogenosPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new PatogenosTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? PatogenosPeer::CLASS_DEFAULT : PatogenosPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Patogenos or Criteria object.
	 *
	 * @param      mixed $values Criteria or Patogenos object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePatogenosPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePatogenosPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Patogenos object
		}

		if ($criteria->containsKey(PatogenosPeer::ID) && $criteria->keyContainsValue(PatogenosPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.PatogenosPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePatogenosPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePatogenosPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Patogenos or Criteria object.
	 *
	 * @param      mixed $values Criteria or Patogenos object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePatogenosPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePatogenosPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(PatogenosPeer::ID);
			$selectCriteria->add(PatogenosPeer::ID, $criteria->remove(PatogenosPeer::ID), $comparison);

		} else { // $values is Patogenos object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePatogenosPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePatogenosPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the patogenos table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(PatogenosPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			PatogenosPeer::clearInstancePool();
			PatogenosPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Patogenos or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Patogenos object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			PatogenosPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Patogenos) { // it's a model object
			// invalidate the cache for this single object
			PatogenosPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(PatogenosPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				PatogenosPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			PatogenosPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Patogenos object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Patogenos $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Patogenos $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(PatogenosPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(PatogenosPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(PatogenosPeer::DATABASE_NAME, PatogenosPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Patogenos
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = PatogenosPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(PatogenosPeer::DATABASE_NAME);
		$criteria->add(PatogenosPeer::ID, $pk);

		$v = PatogenosPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PatogenosPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(PatogenosPeer::DATABASE_NAME);
			$criteria->add(PatogenosPeer::ID, $pks, Criteria::IN);
			$objs = PatogenosPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasePatogenosPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BasePatogenosPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasePatogenosPeer::buildTableMap();

