<?php

/**
 * Base class that represents a row from the 'resultado' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 * @package    lib.model.om
 */
abstract class BaseResultado extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ResultadoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the pre_enriq_id field.
	 * @var        int
	 */
	protected $pre_enriq_id;

	/**
	 * The value for the enriq_id field.
	 * @var        int
	 */
	protected $enriq_id;

	/**
	 * The value for the medio_id field.
	 * @var        int
	 */
	protected $medio_id;

	/**
	 * The value for the temp_incubacion_id field.
	 * @var        int
	 */
	protected $temp_incubacion_id;

	/**
	 * The value for the tiempo_incubacion_id field.
	 * @var        int
	 */
	protected $tiempo_incubacion_id;

	/**
	 * The value for the muestra_id field.
	 * @var        int
	 */
	protected $muestra_id;

	/**
	 * @var        PreEnriq
	 */
	protected $aPreEnriq;

	/**
	 * @var        Enriq
	 */
	protected $aEnriq;

	/**
	 * @var        Medio
	 */
	protected $aMedio;

	/**
	 * @var        TempIncubacion
	 */
	protected $aTempIncubacion;

	/**
	 * @var        TiempoIncubacion
	 */
	protected $aTiempoIncubacion;

	/**
	 * @var        Muestra
	 */
	protected $aMuestra;

	/**
	 * @var        array NoPatogeno[] Collection to store aggregation of NoPatogeno objects.
	 */
	protected $collNoPatogenos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collNoPatogenos.
	 */
	private $lastNoPatogenoCriteria = null;

	/**
	 * @var        array Patogenos[] Collection to store aggregation of Patogenos objects.
	 */
	protected $collPatogenoss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPatogenoss.
	 */
	private $lastPatogenosCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ResultadoPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [pre_enriq_id] column value.
	 * 
	 * @return     int
	 */
	public function getPreEnriqId()
	{
		return $this->pre_enriq_id;
	}

	/**
	 * Get the [enriq_id] column value.
	 * 
	 * @return     int
	 */
	public function getEnriqId()
	{
		return $this->enriq_id;
	}

	/**
	 * Get the [medio_id] column value.
	 * 
	 * @return     int
	 */
	public function getMedioId()
	{
		return $this->medio_id;
	}

	/**
	 * Get the [temp_incubacion_id] column value.
	 * 
	 * @return     int
	 */
	public function getTempIncubacionId()
	{
		return $this->temp_incubacion_id;
	}

	/**
	 * Get the [tiempo_incubacion_id] column value.
	 * 
	 * @return     int
	 */
	public function getTiempoIncubacionId()
	{
		return $this->tiempo_incubacion_id;
	}

	/**
	 * Get the [muestra_id] column value.
	 * 
	 * @return     int
	 */
	public function getMuestraId()
	{
		return $this->muestra_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ResultadoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ResultadoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ResultadoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [pre_enriq_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setPreEnriqId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pre_enriq_id !== $v) {
			$this->pre_enriq_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::PRE_ENRIQ_ID;
		}

		if ($this->aPreEnriq !== null && $this->aPreEnriq->getId() !== $v) {
			$this->aPreEnriq = null;
		}

		return $this;
	} // setPreEnriqId()

	/**
	 * Set the value of [enriq_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setEnriqId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->enriq_id !== $v) {
			$this->enriq_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::ENRIQ_ID;
		}

		if ($this->aEnriq !== null && $this->aEnriq->getId() !== $v) {
			$this->aEnriq = null;
		}

		return $this;
	} // setEnriqId()

	/**
	 * Set the value of [medio_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setMedioId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->medio_id !== $v) {
			$this->medio_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::MEDIO_ID;
		}

		if ($this->aMedio !== null && $this->aMedio->getId() !== $v) {
			$this->aMedio = null;
		}

		return $this;
	} // setMedioId()

	/**
	 * Set the value of [temp_incubacion_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setTempIncubacionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->temp_incubacion_id !== $v) {
			$this->temp_incubacion_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::TEMP_INCUBACION_ID;
		}

		if ($this->aTempIncubacion !== null && $this->aTempIncubacion->getId() !== $v) {
			$this->aTempIncubacion = null;
		}

		return $this;
	} // setTempIncubacionId()

	/**
	 * Set the value of [tiempo_incubacion_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setTiempoIncubacionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tiempo_incubacion_id !== $v) {
			$this->tiempo_incubacion_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::TIEMPO_INCUBACION_ID;
		}

		if ($this->aTiempoIncubacion !== null && $this->aTiempoIncubacion->getId() !== $v) {
			$this->aTiempoIncubacion = null;
		}

		return $this;
	} // setTiempoIncubacionId()

	/**
	 * Set the value of [muestra_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Resultado The current object (for fluent API support)
	 */
	public function setMuestraId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->muestra_id !== $v) {
			$this->muestra_id = $v;
			$this->modifiedColumns[] = ResultadoPeer::MUESTRA_ID;
		}

		if ($this->aMuestra !== null && $this->aMuestra->getId() !== $v) {
			$this->aMuestra = null;
		}

		return $this;
	} // setMuestraId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->created_at = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->updated_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->pre_enriq_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->enriq_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->medio_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->temp_incubacion_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->tiempo_incubacion_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->muestra_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = ResultadoPeer::NUM_COLUMNS - ResultadoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Resultado object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPreEnriq !== null && $this->pre_enriq_id !== $this->aPreEnriq->getId()) {
			$this->aPreEnriq = null;
		}
		if ($this->aEnriq !== null && $this->enriq_id !== $this->aEnriq->getId()) {
			$this->aEnriq = null;
		}
		if ($this->aMedio !== null && $this->medio_id !== $this->aMedio->getId()) {
			$this->aMedio = null;
		}
		if ($this->aTempIncubacion !== null && $this->temp_incubacion_id !== $this->aTempIncubacion->getId()) {
			$this->aTempIncubacion = null;
		}
		if ($this->aTiempoIncubacion !== null && $this->tiempo_incubacion_id !== $this->aTiempoIncubacion->getId()) {
			$this->aTiempoIncubacion = null;
		}
		if ($this->aMuestra !== null && $this->muestra_id !== $this->aMuestra->getId()) {
			$this->aMuestra = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ResultadoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ResultadoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPreEnriq = null;
			$this->aEnriq = null;
			$this->aMedio = null;
			$this->aTempIncubacion = null;
			$this->aTiempoIncubacion = null;
			$this->aMuestra = null;
			$this->collNoPatogenos = null;
			$this->lastNoPatogenoCriteria = null;

			$this->collPatogenoss = null;
			$this->lastPatogenosCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ResultadoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseResultado:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ResultadoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseResultado:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ResultadoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseResultado:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(ResultadoPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(ResultadoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseResultado:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ResultadoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPreEnriq !== null) {
				if ($this->aPreEnriq->isModified() || $this->aPreEnriq->isNew()) {
					$affectedRows += $this->aPreEnriq->save($con);
				}
				$this->setPreEnriq($this->aPreEnriq);
			}

			if ($this->aEnriq !== null) {
				if ($this->aEnriq->isModified() || $this->aEnriq->isNew()) {
					$affectedRows += $this->aEnriq->save($con);
				}
				$this->setEnriq($this->aEnriq);
			}

			if ($this->aMedio !== null) {
				if ($this->aMedio->isModified() || $this->aMedio->isNew()) {
					$affectedRows += $this->aMedio->save($con);
				}
				$this->setMedio($this->aMedio);
			}

			if ($this->aTempIncubacion !== null) {
				if ($this->aTempIncubacion->isModified() || $this->aTempIncubacion->isNew()) {
					$affectedRows += $this->aTempIncubacion->save($con);
				}
				$this->setTempIncubacion($this->aTempIncubacion);
			}

			if ($this->aTiempoIncubacion !== null) {
				if ($this->aTiempoIncubacion->isModified() || $this->aTiempoIncubacion->isNew()) {
					$affectedRows += $this->aTiempoIncubacion->save($con);
				}
				$this->setTiempoIncubacion($this->aTiempoIncubacion);
			}

			if ($this->aMuestra !== null) {
				if ($this->aMuestra->isModified() || $this->aMuestra->isNew()) {
					$affectedRows += $this->aMuestra->save($con);
				}
				$this->setMuestra($this->aMuestra);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ResultadoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ResultadoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ResultadoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collNoPatogenos !== null) {
				foreach ($this->collNoPatogenos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPatogenoss !== null) {
				foreach ($this->collPatogenoss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPreEnriq !== null) {
				if (!$this->aPreEnriq->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPreEnriq->getValidationFailures());
				}
			}

			if ($this->aEnriq !== null) {
				if (!$this->aEnriq->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEnriq->getValidationFailures());
				}
			}

			if ($this->aMedio !== null) {
				if (!$this->aMedio->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMedio->getValidationFailures());
				}
			}

			if ($this->aTempIncubacion !== null) {
				if (!$this->aTempIncubacion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTempIncubacion->getValidationFailures());
				}
			}

			if ($this->aTiempoIncubacion !== null) {
				if (!$this->aTiempoIncubacion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTiempoIncubacion->getValidationFailures());
				}
			}

			if ($this->aMuestra !== null) {
				if (!$this->aMuestra->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMuestra->getValidationFailures());
				}
			}


			if (($retval = ResultadoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collNoPatogenos !== null) {
					foreach ($this->collNoPatogenos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPatogenoss !== null) {
					foreach ($this->collPatogenoss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ResultadoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCreatedAt();
				break;
			case 2:
				return $this->getUpdatedAt();
				break;
			case 3:
				return $this->getPreEnriqId();
				break;
			case 4:
				return $this->getEnriqId();
				break;
			case 5:
				return $this->getMedioId();
				break;
			case 6:
				return $this->getTempIncubacionId();
				break;
			case 7:
				return $this->getTiempoIncubacionId();
				break;
			case 8:
				return $this->getMuestraId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ResultadoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCreatedAt(),
			$keys[2] => $this->getUpdatedAt(),
			$keys[3] => $this->getPreEnriqId(),
			$keys[4] => $this->getEnriqId(),
			$keys[5] => $this->getMedioId(),
			$keys[6] => $this->getTempIncubacionId(),
			$keys[7] => $this->getTiempoIncubacionId(),
			$keys[8] => $this->getMuestraId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ResultadoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCreatedAt($value);
				break;
			case 2:
				$this->setUpdatedAt($value);
				break;
			case 3:
				$this->setPreEnriqId($value);
				break;
			case 4:
				$this->setEnriqId($value);
				break;
			case 5:
				$this->setMedioId($value);
				break;
			case 6:
				$this->setTempIncubacionId($value);
				break;
			case 7:
				$this->setTiempoIncubacionId($value);
				break;
			case 8:
				$this->setMuestraId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ResultadoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCreatedAt($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUpdatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPreEnriqId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEnriqId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMedioId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTempIncubacionId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTiempoIncubacionId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setMuestraId($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);

		if ($this->isColumnModified(ResultadoPeer::ID)) $criteria->add(ResultadoPeer::ID, $this->id);
		if ($this->isColumnModified(ResultadoPeer::CREATED_AT)) $criteria->add(ResultadoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(ResultadoPeer::UPDATED_AT)) $criteria->add(ResultadoPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(ResultadoPeer::PRE_ENRIQ_ID)) $criteria->add(ResultadoPeer::PRE_ENRIQ_ID, $this->pre_enriq_id);
		if ($this->isColumnModified(ResultadoPeer::ENRIQ_ID)) $criteria->add(ResultadoPeer::ENRIQ_ID, $this->enriq_id);
		if ($this->isColumnModified(ResultadoPeer::MEDIO_ID)) $criteria->add(ResultadoPeer::MEDIO_ID, $this->medio_id);
		if ($this->isColumnModified(ResultadoPeer::TEMP_INCUBACION_ID)) $criteria->add(ResultadoPeer::TEMP_INCUBACION_ID, $this->temp_incubacion_id);
		if ($this->isColumnModified(ResultadoPeer::TIEMPO_INCUBACION_ID)) $criteria->add(ResultadoPeer::TIEMPO_INCUBACION_ID, $this->tiempo_incubacion_id);
		if ($this->isColumnModified(ResultadoPeer::MUESTRA_ID)) $criteria->add(ResultadoPeer::MUESTRA_ID, $this->muestra_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);

		$criteria->add(ResultadoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Resultado (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setPreEnriqId($this->pre_enriq_id);

		$copyObj->setEnriqId($this->enriq_id);

		$copyObj->setMedioId($this->medio_id);

		$copyObj->setTempIncubacionId($this->temp_incubacion_id);

		$copyObj->setTiempoIncubacionId($this->tiempo_incubacion_id);

		$copyObj->setMuestraId($this->muestra_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getNoPatogenos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addNoPatogeno($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPatogenoss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPatogenos($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Resultado Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ResultadoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ResultadoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a PreEnriq object.
	 *
	 * @param      PreEnriq $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPreEnriq(PreEnriq $v = null)
	{
		if ($v === null) {
			$this->setPreEnriqId(NULL);
		} else {
			$this->setPreEnriqId($v->getId());
		}

		$this->aPreEnriq = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PreEnriq object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated PreEnriq object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PreEnriq The associated PreEnriq object.
	 * @throws     PropelException
	 */
	public function getPreEnriq(PropelPDO $con = null)
	{
		if ($this->aPreEnriq === null && ($this->pre_enriq_id !== null)) {
			$this->aPreEnriq = PreEnriqPeer::retrieveByPk($this->pre_enriq_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPreEnriq->addResultados($this);
			 */
		}
		return $this->aPreEnriq;
	}

	/**
	 * Declares an association between this object and a Enriq object.
	 *
	 * @param      Enriq $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEnriq(Enriq $v = null)
	{
		if ($v === null) {
			$this->setEnriqId(NULL);
		} else {
			$this->setEnriqId($v->getId());
		}

		$this->aEnriq = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Enriq object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated Enriq object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Enriq The associated Enriq object.
	 * @throws     PropelException
	 */
	public function getEnriq(PropelPDO $con = null)
	{
		if ($this->aEnriq === null && ($this->enriq_id !== null)) {
			$this->aEnriq = EnriqPeer::retrieveByPk($this->enriq_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEnriq->addResultados($this);
			 */
		}
		return $this->aEnriq;
	}

	/**
	 * Declares an association between this object and a Medio object.
	 *
	 * @param      Medio $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMedio(Medio $v = null)
	{
		if ($v === null) {
			$this->setMedioId(NULL);
		} else {
			$this->setMedioId($v->getId());
		}

		$this->aMedio = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Medio object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated Medio object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Medio The associated Medio object.
	 * @throws     PropelException
	 */
	public function getMedio(PropelPDO $con = null)
	{
		if ($this->aMedio === null && ($this->medio_id !== null)) {
			$this->aMedio = MedioPeer::retrieveByPk($this->medio_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMedio->addResultados($this);
			 */
		}
		return $this->aMedio;
	}

	/**
	 * Declares an association between this object and a TempIncubacion object.
	 *
	 * @param      TempIncubacion $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTempIncubacion(TempIncubacion $v = null)
	{
		if ($v === null) {
			$this->setTempIncubacionId(NULL);
		} else {
			$this->setTempIncubacionId($v->getId());
		}

		$this->aTempIncubacion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TempIncubacion object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated TempIncubacion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TempIncubacion The associated TempIncubacion object.
	 * @throws     PropelException
	 */
	public function getTempIncubacion(PropelPDO $con = null)
	{
		if ($this->aTempIncubacion === null && ($this->temp_incubacion_id !== null)) {
			$this->aTempIncubacion = TempIncubacionPeer::retrieveByPk($this->temp_incubacion_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTempIncubacion->addResultados($this);
			 */
		}
		return $this->aTempIncubacion;
	}

	/**
	 * Declares an association between this object and a TiempoIncubacion object.
	 *
	 * @param      TiempoIncubacion $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTiempoIncubacion(TiempoIncubacion $v = null)
	{
		if ($v === null) {
			$this->setTiempoIncubacionId(NULL);
		} else {
			$this->setTiempoIncubacionId($v->getId());
		}

		$this->aTiempoIncubacion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TiempoIncubacion object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated TiempoIncubacion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TiempoIncubacion The associated TiempoIncubacion object.
	 * @throws     PropelException
	 */
	public function getTiempoIncubacion(PropelPDO $con = null)
	{
		if ($this->aTiempoIncubacion === null && ($this->tiempo_incubacion_id !== null)) {
			$this->aTiempoIncubacion = TiempoIncubacionPeer::retrieveByPk($this->tiempo_incubacion_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTiempoIncubacion->addResultados($this);
			 */
		}
		return $this->aTiempoIncubacion;
	}

	/**
	 * Declares an association between this object and a Muestra object.
	 *
	 * @param      Muestra $v
	 * @return     Resultado The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMuestra(Muestra $v = null)
	{
		if ($v === null) {
			$this->setMuestraId(NULL);
		} else {
			$this->setMuestraId($v->getId());
		}

		$this->aMuestra = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Muestra object, it will not be re-added.
		if ($v !== null) {
			$v->addResultado($this);
		}

		return $this;
	}


	/**
	 * Get the associated Muestra object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Muestra The associated Muestra object.
	 * @throws     PropelException
	 */
	public function getMuestra(PropelPDO $con = null)
	{
		if ($this->aMuestra === null && ($this->muestra_id !== null)) {
			$this->aMuestra = MuestraPeer::retrieveByPk($this->muestra_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMuestra->addResultados($this);
			 */
		}
		return $this->aMuestra;
	}

	/**
	 * Clears out the collNoPatogenos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addNoPatogenos()
	 */
	public function clearNoPatogenos()
	{
		$this->collNoPatogenos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collNoPatogenos collection (array).
	 *
	 * By default this just sets the collNoPatogenos collection to an empty array (like clearcollNoPatogenos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initNoPatogenos()
	{
		$this->collNoPatogenos = array();
	}

	/**
	 * Gets an array of NoPatogeno objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Resultado has previously been saved, it will retrieve
	 * related NoPatogenos from storage. If this Resultado is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array NoPatogeno[]
	 * @throws     PropelException
	 */
	public function getNoPatogenos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNoPatogenos === null) {
			if ($this->isNew()) {
			   $this->collNoPatogenos = array();
			} else {

				$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

				NoPatogenoPeer::addSelectColumns($criteria);
				$this->collNoPatogenos = NoPatogenoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

				NoPatogenoPeer::addSelectColumns($criteria);
				if (!isset($this->lastNoPatogenoCriteria) || !$this->lastNoPatogenoCriteria->equals($criteria)) {
					$this->collNoPatogenos = NoPatogenoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastNoPatogenoCriteria = $criteria;
		return $this->collNoPatogenos;
	}

	/**
	 * Returns the number of related NoPatogeno objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related NoPatogeno objects.
	 * @throws     PropelException
	 */
	public function countNoPatogenos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collNoPatogenos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

				$count = NoPatogenoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

				if (!isset($this->lastNoPatogenoCriteria) || !$this->lastNoPatogenoCriteria->equals($criteria)) {
					$count = NoPatogenoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collNoPatogenos);
				}
			} else {
				$count = count($this->collNoPatogenos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a NoPatogeno object to this object
	 * through the NoPatogeno foreign key attribute.
	 *
	 * @param      NoPatogeno $l NoPatogeno
	 * @return     void
	 * @throws     PropelException
	 */
	public function addNoPatogeno(NoPatogeno $l)
	{
		if ($this->collNoPatogenos === null) {
			$this->initNoPatogenos();
		}
		if (!in_array($l, $this->collNoPatogenos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collNoPatogenos, $l);
			$l->setResultado($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Resultado is new, it will return
	 * an empty collection; or if this Resultado has previously
	 * been saved, it will retrieve related NoPatogenos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Resultado.
	 */
	public function getNoPatogenosJoinDilucion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNoPatogenos === null) {
			if ($this->isNew()) {
				$this->collNoPatogenos = array();
			} else {

				$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

				$this->collNoPatogenos = NoPatogenoPeer::doSelectJoinDilucion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(NoPatogenoPeer::RESULTADO_ID, $this->id);

			if (!isset($this->lastNoPatogenoCriteria) || !$this->lastNoPatogenoCriteria->equals($criteria)) {
				$this->collNoPatogenos = NoPatogenoPeer::doSelectJoinDilucion($criteria, $con, $join_behavior);
			}
		}
		$this->lastNoPatogenoCriteria = $criteria;

		return $this->collNoPatogenos;
	}

	/**
	 * Clears out the collPatogenoss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPatogenoss()
	 */
	public function clearPatogenoss()
	{
		$this->collPatogenoss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPatogenoss collection (array).
	 *
	 * By default this just sets the collPatogenoss collection to an empty array (like clearcollPatogenoss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPatogenoss()
	{
		$this->collPatogenoss = array();
	}

	/**
	 * Gets an array of Patogenos objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Resultado has previously been saved, it will retrieve
	 * related Patogenoss from storage. If this Resultado is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Patogenos[]
	 * @throws     PropelException
	 */
	public function getPatogenoss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPatogenoss === null) {
			if ($this->isNew()) {
			   $this->collPatogenoss = array();
			} else {

				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				PatogenosPeer::addSelectColumns($criteria);
				$this->collPatogenoss = PatogenosPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				PatogenosPeer::addSelectColumns($criteria);
				if (!isset($this->lastPatogenosCriteria) || !$this->lastPatogenosCriteria->equals($criteria)) {
					$this->collPatogenoss = PatogenosPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPatogenosCriteria = $criteria;
		return $this->collPatogenoss;
	}

	/**
	 * Returns the number of related Patogenos objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Patogenos objects.
	 * @throws     PropelException
	 */
	public function countPatogenoss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPatogenoss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				$count = PatogenosPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				if (!isset($this->lastPatogenosCriteria) || !$this->lastPatogenosCriteria->equals($criteria)) {
					$count = PatogenosPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPatogenoss);
				}
			} else {
				$count = count($this->collPatogenoss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Patogenos object to this object
	 * through the Patogenos foreign key attribute.
	 *
	 * @param      Patogenos $l Patogenos
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPatogenos(Patogenos $l)
	{
		if ($this->collPatogenoss === null) {
			$this->initPatogenoss();
		}
		if (!in_array($l, $this->collPatogenoss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPatogenoss, $l);
			$l->setResultado($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Resultado is new, it will return
	 * an empty collection; or if this Resultado has previously
	 * been saved, it will retrieve related Patogenoss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Resultado.
	 */
	public function getPatogenossJoinCampoResultadoPatogeno($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPatogenoss === null) {
			if ($this->isNew()) {
				$this->collPatogenoss = array();
			} else {

				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				$this->collPatogenoss = PatogenosPeer::doSelectJoinCampoResultadoPatogeno($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

			if (!isset($this->lastPatogenosCriteria) || !$this->lastPatogenosCriteria->equals($criteria)) {
				$this->collPatogenoss = PatogenosPeer::doSelectJoinCampoResultadoPatogeno($criteria, $con, $join_behavior);
			}
		}
		$this->lastPatogenosCriteria = $criteria;

		return $this->collPatogenoss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Resultado is new, it will return
	 * an empty collection; or if this Resultado has previously
	 * been saved, it will retrieve related Patogenoss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Resultado.
	 */
	public function getPatogenossJoinPruebaBioquimica($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPatogenoss === null) {
			if ($this->isNew()) {
				$this->collPatogenoss = array();
			} else {

				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				$this->collPatogenoss = PatogenosPeer::doSelectJoinPruebaBioquimica($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

			if (!isset($this->lastPatogenosCriteria) || !$this->lastPatogenosCriteria->equals($criteria)) {
				$this->collPatogenoss = PatogenosPeer::doSelectJoinPruebaBioquimica($criteria, $con, $join_behavior);
			}
		}
		$this->lastPatogenosCriteria = $criteria;

		return $this->collPatogenoss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Resultado is new, it will return
	 * an empty collection; or if this Resultado has previously
	 * been saved, it will retrieve related Patogenoss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Resultado.
	 */
	public function getPatogenossJoinPositivoNegativo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ResultadoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPatogenoss === null) {
			if ($this->isNew()) {
				$this->collPatogenoss = array();
			} else {

				$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

				$this->collPatogenoss = PatogenosPeer::doSelectJoinPositivoNegativo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PatogenosPeer::RESULTADO_ID, $this->id);

			if (!isset($this->lastPatogenosCriteria) || !$this->lastPatogenosCriteria->equals($criteria)) {
				$this->collPatogenoss = PatogenosPeer::doSelectJoinPositivoNegativo($criteria, $con, $join_behavior);
			}
		}
		$this->lastPatogenosCriteria = $criteria;

		return $this->collPatogenoss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collNoPatogenos) {
				foreach ((array) $this->collNoPatogenos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPatogenoss) {
				foreach ((array) $this->collPatogenoss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collNoPatogenos = null;
		$this->collPatogenoss = null;
			$this->aPreEnriq = null;
			$this->aEnriq = null;
			$this->aMedio = null;
			$this->aTempIncubacion = null;
			$this->aTiempoIncubacion = null;
			$this->aMuestra = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseResultado:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseResultado::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseResultado
