<?php


/**
 * This class defines the structure of the 'no_patogeno' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class NoPatogenoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.NoPatogenoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('no_patogeno');
		$this->setPhpName('NoPatogeno');
		$this->setClassname('NoPatogeno');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('CANTIDAD', 'Cantidad', 'FLOAT', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('RESULTADO_ID', 'ResultadoId', 'INTEGER', 'resultado', 'ID', true, null, null);
		$this->addForeignKey('DILUCION_ID', 'DilucionId', 'INTEGER', 'dilucion', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Resultado', 'Resultado', RelationMap::MANY_TO_ONE, array('resultado_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Dilucion', 'Dilucion', RelationMap::MANY_TO_ONE, array('dilucion_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // NoPatogenoTableMap
