<?php


/**
 * This class defines the structure of the 'patogenos' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PatogenosTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PatogenosTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('patogenos');
		$this->setPhpName('Patogenos');
		$this->setClassname('Patogenos');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NOMBRE_PRUEBA', 'NombrePrueba', 'VARCHAR', false, 45, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('RESULTADO_ID', 'ResultadoId', 'INTEGER', 'resultado', 'ID', true, null, null);
		$this->addForeignKey('CAMPO_RESULTADO_PATOGENO_ID', 'CampoResultadoPatogenoId', 'INTEGER', 'campo_resultado_patogeno', 'ID', true, null, null);
		$this->addForeignKey('PRUEBA_BIOQUIMICA_ID', 'PruebaBioquimicaId', 'INTEGER', 'prueba_bioquimica', 'ID', true, null, null);
		$this->addForeignKey('POSITIVO_NEGATIVO_ID', 'PositivoNegativoId', 'INTEGER', 'positivo_negativo', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Resultado', 'Resultado', RelationMap::MANY_TO_ONE, array('resultado_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('CampoResultadoPatogeno', 'CampoResultadoPatogeno', RelationMap::MANY_TO_ONE, array('campo_resultado_patogeno_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('PruebaBioquimica', 'PruebaBioquimica', RelationMap::MANY_TO_ONE, array('prueba_bioquimica_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('PositivoNegativo', 'PositivoNegativo', RelationMap::MANY_TO_ONE, array('positivo_negativo_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PatogenosTableMap
