<?php


/**
 * This class defines the structure of the 'resultado' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/08/13 15:58:30
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ResultadoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ResultadoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('resultado');
		$this->setPhpName('Resultado');
		$this->setClassname('Resultado');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('PRE_ENRIQ_ID', 'PreEnriqId', 'INTEGER', 'pre_enriq', 'ID', true, null, null);
		$this->addForeignKey('ENRIQ_ID', 'EnriqId', 'INTEGER', 'enriq', 'ID', true, null, null);
		$this->addForeignKey('MEDIO_ID', 'MedioId', 'INTEGER', 'medio', 'ID', true, null, null);
		$this->addForeignKey('TEMP_INCUBACION_ID', 'TempIncubacionId', 'INTEGER', 'temp_incubacion', 'ID', true, null, null);
		$this->addForeignKey('TIEMPO_INCUBACION_ID', 'TiempoIncubacionId', 'INTEGER', 'tiempo_incubacion', 'ID', true, null, null);
		$this->addForeignKey('MUESTRA_ID', 'MuestraId', 'INTEGER', 'muestra', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('PreEnriq', 'PreEnriq', RelationMap::MANY_TO_ONE, array('pre_enriq_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Enriq', 'Enriq', RelationMap::MANY_TO_ONE, array('enriq_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Medio', 'Medio', RelationMap::MANY_TO_ONE, array('medio_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('TempIncubacion', 'TempIncubacion', RelationMap::MANY_TO_ONE, array('temp_incubacion_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('TiempoIncubacion', 'TiempoIncubacion', RelationMap::MANY_TO_ONE, array('tiempo_incubacion_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Muestra', 'Muestra', RelationMap::MANY_TO_ONE, array('muestra_id' => 'id', ), null, null);
    $this->addRelation('NoPatogeno', 'NoPatogeno', RelationMap::ONE_TO_MANY, array('id' => 'resultado_id', ), 'CASCADE', null);
    $this->addRelation('Patogenos', 'Patogenos', RelationMap::ONE_TO_MANY, array('id' => 'resultado_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ResultadoTableMap
