<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/08 15:58:53
sfConfig::add(array(
  'app_sf_guard_plugin_profile_class' => 'UserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
));
