generator:
  class: sfPropelGenerator
  param:
    model_class:           PositivoNegativo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              PositivoNegativo
    plural:                PositivoNegativos
    route_prefix:          positivo_negativo
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Resultado
        display: [=resultado]
      filter:  
        display: [resultado]
      form:    ~
      edit:    ~
      new:     ~
